apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-manager
spec:
  selector:
    app: backend        # ← yeh pods ko dhundta hai
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP