apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: "{{ .Values.namespaceName }}"
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: "{{ .Values.backend.port }}"
          resources:
            requests:
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
              memory: "{{ .Values.backend.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
              memory: "{{ .Values.backend.resources.limits.memory }}"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: task-manager-config
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: task-manager-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-manager-secret
                  key: DB_PASSWORD